FROM postgres:17

# Copia el archivo de configuración personalizado de PostgreSQL
COPY pg_logs/PostgreSQL.conf /etc/postgresql/postgresql.conf

# Instalar la extensión pgaudit
RUN apt-get update && \
    apt-get install -y postgresql-contrib && \
    apt-get install -y postgresql-17-pgaudit && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Comando para iniciar PostgreSQL con la configuración personalizada
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
