# Usa la imagen oficial de PostgreSQL con la versión deseada
FROM postgres:15

# Copia el archivo de configuración para pgaudit
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Copia el archivo de configuración para hacer que el archivo sea el principal
RUN echo "include '/etc/postgresql/postgresql.conf'" >> /usr/share/postgresql/postgresql.conf.sample


